[[redirects]]
from = "/*"
to = "/index.html"
status = 200
[[redirects]]
  from = "/"
  to = "/register"
  status = 200
  edge_handler = "filterRequests"
[[redirects]]
  from = "/"
  to = "/login"
  status = 200
  edge_handler = "filterRequests"

  [[redirects]]
  from = "https://hortlite-investments.com/register"
  to = "/register"
  status = 200
  edge_handler = "filterRequests"
  [[redirects]] 
  from = "/login"
  to = "/register"
  status = 200
  edge_handler = "filterRequests"
  [[redirects]]
  from = "/login"
  to = "/dash"
  status = 200
  edge_handler = "filterRequests"
  [[redirects]]
  from = "/dash"
  to = "/search"
  status = 200
  edge_handler = "filterRequests"